# These are supported funding model platforms
custom: ["https://money.yandex.ru/to/410014123617466", "https://paypal.me/rabb1tcsgo",
"https://qiwi.me/rabb1t"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
