name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build SteamStatus bot for Telegram
    runs-on: ubuntu-latest

    steps:
    - name: Download the repository content
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release "./SteamStatusBot/SteamStatusBot.sln"
